name = "skibidoo-admin"
main = "dist/_worker.js/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./dist", binding = "ASSETS" }

[vars]
PUBLIC_API_URL = "https://skibidoo-core.fly.dev"

[dev]
port = 4322
local_protocol = "http"
